name: sync
channels:
  - conda-forge
dependencies:
  - altair=5.0.1=pyhd8ed1ab_1
  - anyio=3.7.1=pyhd8ed1ab_0
  - aom=3.5.0=h7ea286d_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311he2be06e_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - audioread=3.0.0=py311h267d04e_1
  - automat=22.10.0=pyhd8ed1ab_0
  - aws-c-auth=0.7.3=hab8b942_3
  - aws-c-cal=0.6.2=hb406d48_0
  - aws-c-common=0.9.0=hb547adb_0
  - aws-c-compression=0.2.17=he70778a_2
  - aws-c-event-stream=0.3.2=hcf14f3f_0
  - aws-c-http=0.7.12=he297698_1
  - aws-c-io=0.13.32=h3c776e5_2
  - aws-c-mqtt=0.9.5=h83b98fe_1
  - aws-c-s3=0.3.14=h24e141d_3
  - aws-c-sdkutils=0.1.12=he70778a_1
  - aws-checksums=0.1.17=he70778a_1
  - aws-crt-cpp=0.23.0=h04fc39a_5
  - aws-sdk-cpp=1.10.57=h0092a47_21
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bcrypt=3.2.2=py311he2be06e_1
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotli=1.0.9=h1a8c8d9_9
  - brotli-bin=1.0.9=h1a8c8d9_9
  - brotli-python=1.0.9=py311ha397e9f_9
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.19.1=hb547adb_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=hc5b65c1_1017
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311hae827db_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - comm=0.1.4=pyhd8ed1ab_0
  - constantly=15.1.0=py_0
  - contourpy=1.1.0=py311he4fd1f5_0
  - cryptography=41.0.3=py311h5fb2c35_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.6.8=py311ha891d26_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dnspython=2.4.2=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_1
  - ffmpeg=6.0.0=gpl_hb1d784b_104
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py311heffc1b2_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hd633e50_1
  - fribidi=1.0.10=h27ca646_0
  - gettext=0.21.1=h0186832_0
  - gflags=2.2.2=hc88da5d_1004
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.32=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.13=h9f76cd9_1001
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=8.1.1=hf1a6348_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.17.3=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - hyperlink=21.0.0=pyhd3deb0d_0
  - icu=73.2=hc8870d7_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - incremental=22.10.0=pyhd8ed1ab_0
  - ipykernel=6.25.1=pyh5fb750a_0
  - ipython=8.14.0=pyhd1c38e8_0
  - ipywidgets=8.1.0=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.19.0=pyhd8ed1ab_1
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.0=pyhd8ed1ab_1
  - jupyter=1.0.0=py311h267d04e_8
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h267d04e_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.1=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py311he4fd1f5_0
  - krb5=1.21.2=h92f50d5_0
  - lame=3.100=h1a8c8d9_1003
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.15=hd835a16_1
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230125.3=cxx17_h13dd4ca_0
  - libarrow=13.0.0=h6e4acf5_0_cpu
  - libass=0.17.1=hf7da4fe_1
  - libblas=3.9.0=17_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_9
  - libbrotlidec=1.0.9=h1a8c8d9_9
  - libbrotlienc=1.0.9=h1a8c8d9_9
  - libcblas=3.9.0=17_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.2.1=hc52a3a8_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.18=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.12=h2757513_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.2=h3422bc3_5
  - libflac=1.4.3=hb765f3a_0
  - libgfortran=5.0.0=12_3_0_hd922786_1
  - libgfortran5=12.3.0=ha3a6a3e_1
  - libglib=2.76.4=h24e9cb9_0
  - libgoogle-cloud=2.12.0=h05652e3_1
  - libgrpc=1.56.2=h9075ed4_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - libjpeg-turbo=2.1.5.1=h1a8c8d9_0
  - liblapack=3.9.0=17_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - libnghttp2=1.52.0=hae82a92_0
  - libogg=1.3.4=h27ca646_1
  - libopenblas=0.3.23=openmp_hc731615_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=4.23.3=hf32f9b9_0
  - librosa=0.10.1=pyhd8ed1ab_0
  - libsndfile=1.2.2=h28b71a8_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.43.0=hb31c410_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtasn1=4.19.0=h1a8c8d9_0
  - libthrift=0.18.1=ha061701_2
  - libtiff=4.5.1=h23a1a89_1
  - libunistring=0.9.10=h3422bc3_0
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.13.0=h7ea286d_0
  - libwebp-base=1.3.1=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.11.5=h25269f3_1
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=16.0.6=h1c12783_0
  - llvmlite=0.40.1=py311hea943cd_0
  - lz4-c=1.9.4=hb7217d7_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311heffc1b2_0
  - matplotlib=3.7.2=py311ha1ab1f8_0
  - matplotlib-base=3.7.2=py311h3bc9839_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mido=1.2.10=pyhd8ed1ab_0
  - mistune=3.0.1=pyhd8ed1ab_0
  - mongoengine=0.26.0=py311h267d04e_0
  - mpg123=1.31.3=hb7217d7_0
  - msgpack-python=1.0.5=py311hd6ee22a_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.7.4=pyhd8ed1ab_0
  - nbconvert-core=7.7.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.7.4=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h7ea286d_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h63371fa_1
  - notebook=7.0.2=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numba=0.57.1=py311hbf3c4e2_0
  - numpy=1.24.4=py311hb8f3215_0
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.1.2=h53f4e23_0
  - orc=1.9.0=h858f345_1
  - overrides=7.4.0=pyhd8ed1ab_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py311h9e438b8_1
  - pandoc=3.1.3=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311h095fde6_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311he2be06e_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=13.0.0=py311hd7bc329_0_cpu
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pymongo=4.5.0=py311ha891d26_0
  - pympler=1.0.1=pyhd8ed1ab_0
  - pyobjc-core=9.2=py311hb702dc4_0
  - pyobjc-framework-cocoa=9.2=py311hb702dc4_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.11.4=h47c9636_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py311h267d04e_3
  - pyyaml=6.0.1=py311heffc1b2_0
  - pyzmq=25.1.1=py311hb1af645_0
  - re2=2023.03.02=hc5e2d97_0
  - readline=8.2=h92ec313_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.5.1=pyhd8ed1ab_0
  - rpds-py=0.9.2=py311h0563b04_0
  - scikit-learn=1.3.0=py311hf0b18b8_0
  - scipy=1.11.2=py311h93d07a4_0
  - send2trash=1.8.2=pyhd1c38e8_0
  - service_identity=18.1.0=py_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - soxr=0.1.3=h5008568_3
  - soxr-python=0.3.5=py311hb49d859_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - streamlit=1.26.0=pyhd8ed1ab_0
  - svt-av1=1.7.0=hb765f3a_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.3.3=py311heffc1b2_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - twisted=22.10.0=py311he2be06e_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - tzlocal=4.3=py311h267d04e_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - validators=0.21.2=pyhd8ed1ab_0
  - watchdog=3.0.0=py311he2be06e_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.2=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zope.interface=6.0=py311he2be06e_0
  - zstd=1.5.2=h4f39d0f_7
  - pip:
      - absl-py==1.4.0
      - flatbuffers==23.5.26
      - mediapipe==0.10.5
      - opencv-contrib-python==4.8.0.76
      - opencv-python==4.8.0.76
      - protobuf==3.20.3
      - python-osc==1.8.3
      - python-rtmidi==1.5.5
      - sounddevice==0.4.6
